# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "ruby"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "ql"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch', 'version-update:semver-minor']

  - package-ecosystem: "gomod"
    directory: "go/extractor"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "golang.org/x/mod"
      - dependency-name: "golang.org/x/tools"
    groups:
      extractor-dependencies:
        patterns:
          - "golang.org/x/*"
    reviewers:
      - "github/codeql-go"

  - package-ecosystem: "gomod"
    directory: "go/ql/test"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
    reviewers:
      - "github/codeql-go"
